# SITE CONFIGURATION
baseurl: "http://gingerninja.me/" # the subpath of your site, e.g. /blog/
url: "http://gingerninja.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Teja Theegala"
  avatar: "129af2e.jpg"
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines


  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "sriteja23@gmail.com"# Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "TejaTheegala"
  flickr:
  github: "GingerNinja23"
  google_plus: "+TejaTheegala"
  instagram:
  linkedin:  "http://in.linkedin.com/in/tejatheegala"# Full URL
  pinterest:
  reddit: "gingerninja23"
  soundcloud:
  stack_exchange:  "users/2557681/gingerninja23"# Full URL
  steam:
  tumblr:
  twitter: "ringo279"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-62589624-1"# Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
